# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clear_trslr.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormClearTranslator(object):
    def setupUi(self, FormClearTranslator):
        FormClearTranslator.setObjectName("FormClearTranslator")
        FormClearTranslator.resize(643, 305)
        self.label = QtWidgets.QLabel(FormClearTranslator)
        self.label.setGeometry(QtCore.QRect(210, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelTask = QtWidgets.QLabel(FormClearTranslator)
        self.labelTask.setGeometry(QtCore.QRect(20, 80, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.labelTask.setFont(font)
        self.labelTask.setWordWrap(True)
        self.labelTask.setObjectName("labelTask")
        self.lineAnswer = QtWidgets.QLineEdit(FormClearTranslator)
        self.lineAnswer.setGeometry(QtCore.QRect(120, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineAnswer.setFont(font)
        self.lineAnswer.setObjectName("lineAnswer")
        self.progressBar = QtWidgets.QProgressBar(FormClearTranslator)
        self.progressBar.setGeometry(QtCore.QRect(10, 270, 621, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btnEnter = QtWidgets.QPushButton(FormClearTranslator)
        self.btnEnter.setGeometry(QtCore.QRect(380, 150, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.btnEnter.setFont(font)
        self.btnEnter.setObjectName("btnEnter")
        self.btnBack = QtWidgets.QPushButton(FormClearTranslator)
        self.btnBack.setGeometry(QtCore.QRect(530, 220, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.labelRightAnswer = QtWidgets.QLabel(FormClearTranslator)
        self.labelRightAnswer.setGeometry(QtCore.QRect(80, 200, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.labelRightAnswer.setFont(font)
        self.labelRightAnswer.setWordWrap(True)
        self.labelRightAnswer.setObjectName("labelRightAnswer")
        self.lcdNumber = QtWidgets.QLCDNumber(FormClearTranslator)
        self.lcdNumber.setGeometry(QtCore.QRect(550, 30, 81, 51))
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(FormClearTranslator)
        QtCore.QMetaObject.connectSlotsByName(FormClearTranslator)

    def retranslateUi(self, FormClearTranslator):
        _translate = QtCore.QCoreApplication.translate
        FormClearTranslator.setWindowTitle(_translate("FormClearTranslator", "Form"))
        self.label.setText(_translate("FormClearTranslator", "Переведите слово"))
        self.labelTask.setText(_translate("FormClearTranslator", "TextLabel"))
        self.btnEnter.setText(_translate("FormClearTranslator", "Enter"))
        self.btnBack.setText(_translate("FormClearTranslator", "Back"))
        self.labelRightAnswer.setText(_translate("FormClearTranslator", "TextLabel"))
