# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oof_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormOOFMain(object):
    def setupUi(self, FormOOFMain):
        FormOOFMain.setObjectName("FormOOFMain")
        FormOOFMain.resize(625, 533)
        self.labelTitle = QtWidgets.QLabel(FormOOFMain)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.btnA = QtWidgets.QPushButton(FormOOFMain)
        self.btnA.setGeometry(QtCore.QRect(30, 140, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.btnA.setFont(font)
        self.btnA.setObjectName("btnA")
        self.btnB = QtWidgets.QPushButton(FormOOFMain)
        self.btnB.setGeometry(QtCore.QRect(30, 220, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.btnB.setFont(font)
        self.btnB.setObjectName("btnB")
        self.btnD = QtWidgets.QPushButton(FormOOFMain)
        self.btnD.setGeometry(QtCore.QRect(30, 400, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.btnD.setFont(font)
        self.btnD.setObjectName("btnD")
        self.btnC = QtWidgets.QPushButton(FormOOFMain)
        self.btnC.setGeometry(QtCore.QRect(30, 310, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.btnC.setFont(font)
        self.btnC.setObjectName("btnC")
        self.labelTask = QtWidgets.QLabel(FormOOFMain)
        self.labelTask.setGeometry(QtCore.QRect(16, 70, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.labelTask.setFont(font)
        self.labelTask.setObjectName("labelTask")
        self.progressBar = QtWidgets.QProgressBar(FormOOFMain)
        self.progressBar.setGeometry(QtCore.QRect(0, 490, 621, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(FormOOFMain)
        self.pushButton.setGeometry(QtCore.QRect(554, 412, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lcdNumber = QtWidgets.QLCDNumber(FormOOFMain)
        self.lcdNumber.setGeometry(QtCore.QRect(500, 60, 121, 61))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setProperty("value", 30.0)
        self.lcdNumber.setProperty("intValue", 30)
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(FormOOFMain)
        QtCore.QMetaObject.connectSlotsByName(FormOOFMain)

    def retranslateUi(self, FormOOFMain):
        _translate = QtCore.QCoreApplication.translate
        FormOOFMain.setWindowTitle(_translate("FormOOFMain", "Form"))
        self.labelTitle.setText(_translate("FormOOFMain", "Подберите правильный перевод:"))
        self.btnA.setText(_translate("FormOOFMain", "PushButton"))
        self.btnB.setText(_translate("FormOOFMain", "PushButton"))
        self.btnD.setText(_translate("FormOOFMain", "PushButton"))
        self.btnC.setText(_translate("FormOOFMain", "PushButton"))
        self.labelTask.setText(_translate("FormOOFMain", "TextLabel"))
        self.pushButton.setText(_translate("FormOOFMain", "Back"))

