# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTestChoice(object):
    def setupUi(self, FormTestChoice):
        FormTestChoice.setObjectName("FormTestChoice")
        FormTestChoice.resize(428, 589)
        self.btnOOF = QtWidgets.QPushButton(FormTestChoice)
        self.btnOOF.setGeometry(QtCore.QRect(70, 10, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnOOF.setFont(font)
        self.btnOOF.setObjectName("btnOOF")
        self.btnBack = QtWidgets.QPushButton(FormTestChoice)
        self.btnBack.setGeometry(QtCore.QRect(310, 520, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.btnCF = QtWidgets.QPushButton(FormTestChoice)
        self.btnCF.setGeometry(QtCore.QRect(70, 130, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnCF.setFont(font)
        self.btnCF.setObjectName("btnCF")
        self.btnCT = QtWidgets.QPushButton(FormTestChoice)
        self.btnCT.setGeometry(QtCore.QRect(70, 250, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnCT.setFont(font)
        self.btnCT.setObjectName("btnCT")
        self.btnWhyDisabled = QtWidgets.QPushButton(FormTestChoice)
        self.btnWhyDisabled.setGeometry(QtCore.QRect(10, 520, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnWhyDisabled.setFont(font)
        self.btnWhyDisabled.setObjectName("btnWhyDisabled")
        self.btnGallows = QtWidgets.QPushButton(FormTestChoice)
        self.btnGallows.setGeometry(QtCore.QRect(70, 370, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnGallows.setFont(font)
        self.btnGallows.setObjectName("btnGallows")

        self.retranslateUi(FormTestChoice)
        QtCore.QMetaObject.connectSlotsByName(FormTestChoice)

    def retranslateUi(self, FormTestChoice):
        _translate = QtCore.QCoreApplication.translate
        FormTestChoice.setWindowTitle(_translate("FormTestChoice", "Form"))
        self.btnOOF.setText(_translate("FormTestChoice", "One of four"))
        self.btnBack.setText(_translate("FormTestChoice", "Back"))
        self.btnCF.setText(_translate("FormTestChoice", "Couple Finder"))
        self.btnCT.setText(_translate("FormTestChoice", "Clear Translator"))
        self.btnWhyDisabled.setText(_translate("FormTestChoice", "Why test is disabled?"))
        self.btnGallows.setText(_translate("FormTestChoice", "Gallows"))
