# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormWorkTable(object):
    def setupUi(self, FormWorkTable):
        FormWorkTable.setObjectName("FormWorkTable")
        FormWorkTable.resize(772, 614)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        FormWorkTable.setFont(font)
        self.tableWidget = QtWidgets.QTableWidget(FormWorkTable)
        self.tableWidget.setGeometry(QtCore.QRect(20, 130, 681, 331))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btnNew = QtWidgets.QPushButton(FormWorkTable)
        self.btnNew.setGeometry(QtCore.QRect(20, 480, 111, 51))
        self.btnNew.setObjectName("btnNew")
        self.btnOK = QtWidgets.QPushButton(FormWorkTable)
        self.btnOK.setGeometry(QtCore.QRect(640, 550, 111, 51))
        self.btnOK.setObjectName("btnOK")
        self.btnEdit = QtWidgets.QPushButton(FormWorkTable)
        self.btnEdit.setGeometry(QtCore.QRect(170, 480, 111, 51))
        self.btnEdit.setObjectName("btnEdit")
        self.btnRemove = QtWidgets.QPushButton(FormWorkTable)
        self.btnRemove.setGeometry(QtCore.QRect(320, 480, 111, 51))
        self.btnRemove.setObjectName("btnRemove")
        self.lineEdit = QtWidgets.QLineEdit(FormWorkTable)
        self.lineEdit.setGeometry(QtCore.QRect(160, 89, 291, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.btnSearch = QtWidgets.QPushButton(FormWorkTable)
        self.btnSearch.setGeometry(QtCore.QRect(30, 90, 111, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.label = QtWidgets.QLabel(FormWorkTable)
        self.label.setGeometry(QtCore.QRect(140, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnSearch_2 = QtWidgets.QPushButton(FormWorkTable)
        self.btnSearch_2.setGeometry(QtCore.QRect(470, 90, 131, 31))
        self.btnSearch_2.setObjectName("btnSearch_2")

        self.retranslateUi(FormWorkTable)
        QtCore.QMetaObject.connectSlotsByName(FormWorkTable)

    def retranslateUi(self, FormWorkTable):
        _translate = QtCore.QCoreApplication.translate
        FormWorkTable.setWindowTitle(_translate("FormWorkTable", "Form"))
        self.btnNew.setText(_translate("FormWorkTable", "Add new"))
        self.btnOK.setText(_translate("FormWorkTable", "OK"))
        self.btnEdit.setText(_translate("FormWorkTable", "Edit"))
        self.btnRemove.setText(_translate("FormWorkTable", "Remove"))
        self.btnSearch.setText(_translate("FormWorkTable", "Search:"))
        self.label.setText(_translate("FormWorkTable", "Улучшайте свой словарь!"))
        self.btnSearch_2.setText(_translate("FormWorkTable", "Clean search"))
